word = str(input("Введите любое слово: "))
a = word.count("a")
e = word.count("e") 
i = word.count("i")
o = word.count("o")
u = word.count("u")
print("Количество букв 'a' в строке: ", bool(a) if a == 0 else a)
print("Количество букв 'e' в строке: ", bool(e) if e == 0 else e)
print("Количество букв 'i' в строке: ", bool(i) if i == 0 else i)
print("Количество букв 'o' в строке: ", bool(o) if o == 0 else o)
print("Количество букв 'u' в строке: ", bool(u) if u == 0 else u)