word = str(input("Введите любое слово: "))
a = word.count("a")
e = word.count("e")
o = word.count("o")
i = word.count("i")
u = word.count("u")
sum_glas_let = a + e + o + i + u
print("Количество букв 'a' в строке: ", bool(a) if a == 0 else a)
print("Количество букв 'e' в строке: ", bool(e) if e == 0 else e)
print("Количество букв 'i' в строке: ", bool(i) if i == 0 else i)
print("Количество букв 'o' в строке: ", bool(o) if o == 0 else o)
print("Количество букв 'u' в строке: ", bool(u) if u == 0 else u)
print()
print("Количество гласных букв: ", sum_glas_let)
print("Количество согласных букв: ", len(word) - sum_glas_let)
